[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = ["dotnet publish -c Release -o out"]

[phases.deploy]
cmds = ["dotnet out/RiskPortfolio.Api.dll"]

[start]
cmd = "dotnet out/RiskPortfolio.Api.dll"
